export const MODULES = [
  {
    name: "Automated Job Posting",
    title: "Automated Job Posting",
    desc: "Create and manage job postings efficiently with AI-powered assistance",
    route: "/job-posting",
    angle: 0,
  },
  {
    name: "CV Data Extraction",
    title: "CV Data Extraction",
    desc: "Extract and analyze candidate CVs with advanced parsing technology",
    route: "/cv-upload",
    angle: (Math.PI * 2) / 13,
  },
  {
    name: "Custom MCQ Generation",
    title: "Custom MCQ Generation",
    desc: "Generate tailored assessment questions for precise evaluation",
    route: "/assessments",
    angle: (Math.PI * 2 * 2) / 13,
  },
  {
    name: "Results Management",
    title: "Results Management",
    desc: "View and analyze comprehensive assessment results",
    route: "/results",
    angle: (Math.PI * 2 * 3) / 13,
  },
  {
    name: "Technical Assessment",
    title: "Technical Assessment",
    desc: "Evaluate coding skills with real-time execution challenges",
    route: "/coding-challenges",
    angle: (Math.PI * 2 * 4) / 13,
  },
  {
    name: "Candidate Monitoring",
    title: "Candidate Monitoring",
    desc: "Track candidate progress and maintain assessment integrity",
    route: "/monitoring",
    angle: (Math.PI * 2 * 5) / 13,
  },
  {
    name: "Insights Extraction",
    title: "Insights Extraction",
    desc: "Extract meaningful insights and trends from hiring data",
    route: "/insights",
    angle: (Math.PI * 2 * 6) / 13,
  },
  {
    name: "Interview Scheduling",
    title: "Interview Scheduling",
    desc: "Schedule interviews with Islamic and Gregorian calendar support",
    route: "/scheduling",
    angle: (Math.PI * 2 * 7) / 13,
  },
  {
    name: "AI Interview System",
    title: "AI Interview System",
    desc: "Conduct fully and semi-automated video interviews with AI",
    route: "/ai-interview",
    angle: (Math.PI * 2 * 8) / 13,
  },
  {
    name: "Candidate Recommendation",
    title: "Candidate Recommendation",
    desc: "AI-powered candidate matching and ranking system",
    route: "/recommendations",
    angle: (Math.PI * 2 * 9) / 13,
  },
  {
    name: "User Profile Management",
    title: "User Profile Management",
    desc: "Manage user profiles and role-based permissions",
    route: "/profile",
    angle: (Math.PI * 2 * 10) / 13,
  },
  {
    name: "Notifications",
    title: "Notifications",
    desc: "Real-time alerts and system updates management",
    route: "/notifications",
    angle: (Math.PI * 2 * 11) / 13,
  },
  {
    name: "System Settings",
    title: "System Settings",
    desc: "Configure system preferences and integrations",
    route: "/settings",
    angle: (Math.PI * 2 * 12) / 13,
  }
];